version: "3.5"

services:
  kuma:
    image: louislam/uptime-kuma
    container_name: uptimekuma
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - uptimekuma:/app/data
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  uptimekuma:
    driver_opts:
      type: "nfs"
      o: "addr=22.0.0.2,nolock,soft,rw"
      device: ":/volume2/containers/docker_volumes/uptimekuma"
